import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{api}from'./lib/api';import'./style.css';
const nav=['Dashboard','Entregas','Nova entrega','Moradores','Unidades','Visitantes','Acessos','Histórico de acessos','Câmeras','Mosaico','Ocorrências','Relatórios','Usuários','Configurações','WhatsApp','QR Code','Auditoria','Planos'];
function Login({on}:{on:()=>void}){const[email,setEmail]=useState('superadmin@portariaflow.local'),[password,setPassword]=useState('ChangeMe123!'),[err,setErr]=useState('');async function submit(){try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',r.access_token);on()}catch(e:any){setErr(e.message)}}return <main className="login"><section><h1>PortariaFlow</h1><p>Portaria inteligente multi-condomínio.</p><input value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={submit}>Entrar</button><a>Recuperar senha</a><b>{err}</b></section></main>}
function Card({t,v}:{t:string,v:any}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function App(){const[auth,setAuth]=useState(!!localStorage.getItem('token'));const[page,setPage]=useState('Dashboard');const[data,setData]=useState<any>({});useEffect(()=>{if(auth)api('/dashboard').then(setData).catch(()=>{})},[auth]);if(!auth)return <Login on={()=>setAuth(true)}/>;return <div className="app"><aside><h2>PortariaFlow</h2>{nav.map(n=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}>{n}</button>)}</aside><main><header><h1>{page}</h1><button onClick={()=>document.body.classList.toggle('dark')}>Claro/Escuro</button></header>{page==='Dashboard'&&<section className="grid"><Card t="Entregas pendentes" v={data.pending_deliveries||0}/><Card t="Recebidas hoje" v={data.received_today||0}/><Card t="Aguardando retirada" v={data.waiting_pickup||0}/><Card t="Visitantes no condomínio" v={data.visitors_inside||0}/><Card t="Entradas do dia" v={data.entries_today||0}/><Card t="Saídas do dia" v={data.exits_today||0}/><Card t="Câmeras online" v={data.cameras_online||0}/><Card t="Câmeras offline" v={data.cameras_offline||0}/><Card t="WhatsApp" v={data.whatsapp_status||'desconectado'}/><Card t="Controle de acesso" v={data.access_control_status||'pronto'}/></section>}{page==='Nova entrega'&&<FormDelivery/>}{page==='Entregas'&&<List path="/deliveries"/>}{page==='Moradores'&&<List path="/residents"/>}{page==='Unidades'&&<List path="/units"/>}{page==='Câmeras'&&<CameraForm/>}{page==='Mosaico'&&<Mosaic/>}{page==='Acessos'&&<List path="/access/events"/>}{page==='Relatórios'&&<List path="/reports/summary"/>}{page==='Auditoria'&&<List path="/audit-logs"/>}{['Visitantes','Histórico de acessos','Ocorrências','Usuários','Configurações','WhatsApp','QR Code','Planos'].includes(page)&&<Placeholder page={page}/>}<button className="help">?</button></main></div>}
function List({path}:{path:string}){const[rows,setRows]=useState<any>();useEffect(()=>{api(path).then(setRows).catch(e=>setRows({erro:e.message}))},[path]);return <pre className="panel">{JSON.stringify(rows,null,2)}</pre>}
function FormDelivery(){const[form,setForm]=useState({recipient_name:'',carrier:'',tracking_code:'',delivered_by:'',photo_url:'',notes:''});const[ok,setOk]=useState('');async function save(){const r=await api('/deliveries',{method:'POST',body:JSON.stringify(form)});setOk('Entrega registrada: '+r.protocol)}return <section className="panel form"><h2>Registro rápido de entrega</h2><input placeholder="Destinatário" onChange={e=>setForm({...form,recipient_name:e.target.value})}/><input placeholder="Transportadora" onChange={e=>setForm({...form,carrier:e.target.value})}/><input placeholder="Código de rastreio" onChange={e=>setForm({...form,tracking_code:e.target.value})}/><input placeholder="Quem entregou" onChange={e=>setForm({...form,delivered_by:e.target.value})}/><label className="photo">📷 Tirar foto / Upload<input type="file" accept="image/*" capture="environment" onChange={e=>setForm({...form,photo_url:e.target.files?.[0]?.name||''})}/></label><textarea placeholder="Observações" onChange={e=>setForm({...form,notes:e.target.value})}/><button onClick={save}>Registrar e notificar WhatsApp</button><b>{ok}</b></section>}
function CameraForm(){return <section className="panel"><h2>Cadastro de câmeras</h2><p>Credenciais RTSP são enviadas somente ao backend e armazenadas criptografadas.</p><List path="/cameras"/></section>}
function Mosaic(){return <section className="mosaic">{[1,2,3,4].map(i=><div><span className="cam">▣</span><span>Câmera {i}</span><em>offline</em></div>)}</section>}
function Placeholder({page}:{page:string}){return <section className="panel"><h2>{page}</h2><p>Tela funcional preparada para conectar aos endpoints REST do MVP. Sem dados reais cadastrados.</p><div className="icons">🏠 📦 👥 🏢 🛡️ 📄 ⚙️ ▣ 📡</div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
